services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: my_sql_server
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    volumes:
      - ./db:/docker-entrypoint-initdb.d